# Pandas Basics



The table has one row for each album and several columns

- **artist** - Name of the artist
- **album** - Name of the album
- **released_year** - Year the album was released
- **length_min_sec** - Length of the album (hours,minutes,seconds)
- **genre** - Genre of the album
- **music_recording_sales_millions** - Music recording sales (millions in USD) on [SONG://DATABASE](http://www.song-database.com/)
- **claimed_sales_millions** - Album's claimed sales (millions in USD) on [SONG://DATABASE](http://www.song-database.com/)
- **date_released** - Date on which the album was released
- **soundtrack** - Indicates if the album is the movie soundtrack (Y) or (N)
- **rating_of_friends** - Indicates the rating from your friends from 1 to 10
<br>

You can see the dataset here:

<font size="1">
<table font-size:xx-small style="width:85%">
  <tr>
    <th>Artist</th>
    <th>Album</th> 
    <th>Released</th>
    <th>Length</th>
    <th>Genre</th> 
    <th>Music recording sales (millions)</th>
    <th>Claimed sales (millions)</th>
    <th>Released</th>
    <th>Soundtrack</th>
    <th>Rating (friends)</th>
  </tr>
  <tr>
    <td>Michael Jackson</td>
    <td>Thriller</td> 
    <td>1982</td>
    <td>00:42:19</td>
    <td>Pop, rock, R&B</td>
    <td>46</td>
    <td>65</td>
    <td>30-Nov-82</td>
    <td></td>
    <td>10.0</td>
  </tr>
  <tr>
    <td>AC/DC</td>
    <td>Back in Black</td> 
    <td>1980</td>
    <td>00:42:11</td>
    <td>Hard rock</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td></td>
    <td>8.5</td>
  </tr>
    <tr>
    <td>Pink Floyd</td>
    <td>The Dark Side of the Moon</td> 
    <td>1973</td>
    <td>00:42:49</td>
    <td>Progressive rock</td>
    <td>24.2</td>
    <td>45</td>
    <td>01-Mar-73</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Whitney Houston</td>
    <td>The Bodyguard</td> 
    <td>1992</td>
    <td>00:57:44</td>
    <td>Soundtrack/R&B, soul, pop</td>
    <td>26.1</td>
    <td>50</td>
    <td>25-Jul-80</td>
    <td>Y</td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Meat Loaf</td>
    <td>Bat Out of Hell</td> 
    <td>1977</td>
    <td>00:46:33</td>
    <td>Hard rock, progressive rock</td>
    <td>20.6</td>
    <td>43</td>
    <td>21-Oct-77</td>
    <td></td>
    <td>7.0</td>
  </tr>
    <tr>
    <td>Eagles</td>
    <td>Their Greatest Hits (1971-1975)</td> 
    <td>1976</td>
    <td>00:43:08</td>
    <td>Rock, soft rock, folk rock</td>
    <td>32.2</td>
    <td>42</td>
    <td>17-Feb-76</td>
    <td></td>
    <td>9.5</td>
  </tr>
    <tr>
    <td>Bee Gees</td>
    <td>Saturday Night Fever</td> 
    <td>1977</td>
    <td>1:15:54</td>
    <td>Disco</td>
    <td>20.6</td>
    <td>40</td>
    <td>15-Nov-77</td>
    <td>Y</td>
    <td>9.0</td>
  </tr>
    <tr>
    <td>Fleetwood Mac</td>
    <td>Rumours</td> 
    <td>1977</td>
    <td>00:40:01</td>
    <td>Soft rock</td>
    <td>27.9</td>
    <td>40</td>
    <td>04-Feb-77</td>
    <td></td>
    <td>9.5</td>
  </tr>
</table></font>

<a id="ref1"></a>
<h2 align=center> Importing Data </h2>

We can import the libraries  or dependency like Pandas  using the following command:

In [1]:
import pandas as pd

After the import command, we now have access to a large number of pre-built classes and functions. This assumes the library is installed; in our lab environment all the necessary libraries are installed. One way pandas allows you to work with data is a dataframe. Let's go through the process to go from a comma separated values (**.csv** ) file to a dataframe. This variable **csv_path** stores the path of the  **.csv** ,that is  used as an argument to the **read_csv** function. The result is stored in the object ** df**, this is a common short form used for a variable referring to a Pandas dataframe.

In [2]:
df=pd.read_csv('data/top_selling_albums.csv')

In [3]:
type(df)

pandas.core.frame.DataFrame

We can use the method **head()** to examine the first five rows of a dataframe:

In [6]:
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0

We can use the method **tail()** to examine the last five rows of a dataframe:

In [7]:
df.tail()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

We can use the attribute **shape** to examine the number of rows and columns of a dataframe:

In [8]:
df.shape

(8, 10)

The process for loading an excel file is similar, we use the path of the excel file and the function **read_excel**. The result is a data frame as before:

In [ ]:
#dependency  needed to install file checking package existance with in environment
#!pip install xlrd

In [ ]:
df = pd.read_excel('top_selling_albums.xlsx')
df.head()

We can access the column "Length" and assign it a new dataframe 'x':

In [13]:
x=df[['Length','Released']]
x

    Length  Released
0  0:42:19      1982
1  0:42:11      1980
2  0:42:49      1973
3  0:57:44      1992
4  0:46:33      1977
5  0:43:08      1976
6  1:15:54      1977
7  0:40:01      1977

In [15]:
df.columns

Index(['Artist', 'Album', 'Released', 'Length', 'Genre',
       'Music Recording Sales (millions)', 'Claimed Sales (millions)',
       'Released.1', 'Soundtrack', 'Rating'],
      dtype='object')

In [18]:
df.rename({'Released.1':'Released_date'},axis=1,inplace=True)

In [19]:
df

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released_date,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

 The process is shown in the figure:

<img src = "https://ibm.box.com/shared/static/bz800py5ui4w0kpb0k09lq3k5oegop5v.png" width = 750, align = "center"></a>

 <a id="ref2"></a>
<h2 align=center> Viewing Data and Accessing Data </h2>

You can also assign the value to a series, you can think of a Pandas series as a 1-D dataframe. Just use one bracket:

In [20]:
x=df['Length']
type(x)

pandas.core.series.Series

In [23]:
print(x)

0    0:42:19
1    0:42:11
2    0:42:49
3    0:57:44
4    0:46:33
5    0:43:08
6    1:15:54
7    0:40:01
Name: Length, dtype: object

You can also assign different columns, for example, we can assign the column 'Artist':

In [ ]:
newvar=df[['Released.1']]
newvar

In [ ]:
x=df[['Artist']]
type(x)

#### Assign the variable 'q' to the dataframe that is made up of the column 'Rating':

In [ ]:
#write code here

You can do the same thing for multiple columns; we just put the dataframe name, in this case, **df**, and the name of the multiple column headers enclosed in double brackets. The result is a new dataframe comprised of the specified columns:

In [ ]:
y=df[['Length','Artist','Genre']]
y

The process is shown in the figure:

<img src = "https://ibm.box.com/shared/static/dh9duk3ucuhmmmbixa6ugac6g384m5sq.png" width = 1100, align = "center"></a>

In [27]:
ahmed=df[['Album','Released','Length']]

In [28]:
ahmed

                             Album  Released   Length
0                         Thriller      1982  0:42:19
1                    Back in Black      1980  0:42:11
2        The Dark Side of the Moon      1973  0:42:49
3                    The Bodyguard      1992  0:57:44
4                  Bat Out of Hell      1977  0:46:33
5  Their Greatest Hits (1971-1975)      1976  0:43:08
6             Saturday Night Fever      1977  1:15:54
7                          Rumours      1977  0:40:01

#### Assign the variable 'q' to the dataframe that is made up of the column 'Released' and 'Artist':

In [30]:
q=df[['Released','Artist']]
q

   Released           Artist
0      1982  Michael Jackson
1      1980            AC/DC
2      1973       Pink Floyd
3      1992  Whitney Houston
4      1977        Meat Loaf
5      1976           Eagles
6      1977         Bee Gees
7      1977    Fleetwood Mac

One way to access unique elements is the 'iloc' method, where you can access the 1st row and first column as follows :

In [32]:
df

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released_date,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

In [ ]:
df.iloc[0:2,0:3] # df.iloc[row_index,column_index]
    # df.iloc[from_row_index:to_row_index+1, from_column_index:to_column_index+1]

            Artist          Album  Released
0  Michael Jackson       Thriller      1982
1            AC/DC  Back in Black      1980

Notice something? A series is returned

Let's convert it to table form

In [ ]:
df.iloc[0:2,0:6]

 You can access the 1st 2 rows as follows:

In [ ]:
df.iloc[0:2]

You can access columns with rows as well:

In [ ]:
df.iloc[0:2,0:2]

There is another method call 'loc' which uses names of row and column indexes.
Notice that 'iloc' was using row and column index to access values

In [38]:
df.loc[0:2,['Album']]

                       Album
0                   Thriller
1              Back in Black
2  The Dark Side of the Moon

Access multiple columns by 'loc'

In [ ]:
df.loc[0:2,['Album','Length']]

#### Access the 4th to 6th row:

Trying with iloc it would be

#### Access 5th and rows after 5th with columns starting from Artist till Length

Using iloc

## Adding Column

In [40]:
df['New Artist'] = df['Artist']

In [44]:
df['emp']=None

In [45]:
df

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released_date,Soundtrack,Rating,New Artist,emp
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0,Michael Jackson,None
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5,AC/DC,None
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0,Pink Floyd,None
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5,Whitney Houston,None
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0,Meat Loaf,None
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5,Eagles,None
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0,Bee Gees,None
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5,Fleetwood Mac,None

In [46]:
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released_date,Soundtrack,Rating,New Artist,emp
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0,Michael Jackson,None
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5,AC/DC,None
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0,Pink Floyd,None
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5,Whitney Houston,None
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0,Meat Loaf,None

## Droping Column

In [47]:
df.drop(['emp'], axis=1, inplace=True)

In [52]:
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released_date,Soundtrack,Rating,New Artist
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0,Michael Jackson
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5,AC/DC
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0,Pink Floyd
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5,Whitney Houston
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0,Meat Loaf

In [58]:
df.drop(columns=['New Artist','Rating'],inplace=True)

In [60]:
df

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released_date,Soundtrack
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN

## Object Type of each column

In [61]:
df.dtypes

Artist                               object
Album                                object
Released                              int64
Length                               object
Genre                                object
Music Recording Sales (millions)    float64
Claimed Sales (millions)              int64
Released_date                        object
Soundtrack                           object
dtype: object

## Null values check in Data Frame

In [62]:
df.isnull()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released_date,Soundtrack
0,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,True

In [63]:
df.isnull().sum()

Artist                              0
Album                               0
Released                            0
Length                              0
Genre                               0
Music Recording Sales (millions)    0
Claimed Sales (millions)            0
Released_date                       0
Soundtrack                          6
dtype: int64

## Summary Statistics

In [64]:
df.describe()

          Released  Music Recording Sales (millions)  Claimed Sales (millions)
count     8.000000                          8.000000                  8.000000
mean   1979.250000                         28.125000                 46.125000
std       5.800246                          8.189322                  8.271077
min    1973.000000                         20.600000                 40.000000
25%    1976.750000                         23.300000                 41.500000
50%    1977.000000                         26.750000                 43.500000
75%    1980.500000                         28.975000                 46.250000
max    1992.000000                         46.000000                 65.000000

In [65]:
df.describe(include='all')

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released_date,Soundtrack
count,8,8,8.000000,8,8,8.000000,8.000000,8,2
unique,8,8,NaN,8,8,NaN,NaN,8,1
top,Michael Jackson,Thriller,NaN,0:42:19,"pop, rock, R&B",NaN,NaN,30-Nov-82,Y
freq,1,1,NaN,1,1,NaN,NaN,1,2
mean,NaN,NaN,1979.250000,NaN,NaN,28.125000,46.125000,NaN,NaN
std,NaN,NaN,5.800246,NaN,NaN,8.189322,8.271077,NaN,NaN
min,NaN,NaN,1973.000000,NaN,NaN,20.600000,40.000000,NaN,NaN
25%,NaN,NaN,1976.750000,NaN,NaN,23.300000,41.500000,NaN,NaN
50%,NaN,NaN,1977.000000,NaN,NaN,26.750000,43.500000,NaN,NaN
75%,NaN,NaN,1980.500000,NaN,NaN,28.975000,46.250000,NaN,NaN
max,NaN,NaN,1992.000000,NaN,NaN,46.000000,65.000000,NaN,NaN

## Querying a dataframe

Querying a database means finding some values based on certain conditions. For example you want to find out the albums having rating greater and equal to 9

In [67]:
df=pd.read_csv('data/top_selling_albums.csv')

In [70]:
soundtracks= df[df['Rating']>9.0]

In [71]:
soundtracks

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5

Notice that in the above result all the columns are displayed. If you want to access a specific column, then you can use **loc** for that purpose.

In [72]:
soundtracks_album= df.loc[df['Rating']>=9.0, ['Album']]

In [73]:
soundtracks_album

                       Album
0                   Thriller
1              Back in Black
2  The Dark Side of the Moon

### Task

Find out the albums released during and after the year 1980

In [ ]:
# write code here

# Exercise

Import file **cars.csv** and show following:

    1.) Top five rows
    2.) Last five rows
    3.) No. of rows and columns
    4.) Access 100th to 130th row with any 3 columns
    5.) Object types of each column
    6.) Null values count in each column
    7.) Summary Statistics

In [ ]:
#importing the file
df_cars=pd.read_csv('cars.csv')

In [ ]:
#top 5 rows

In [ ]:
#last 5 rows

In [ ]:
#Access 100th to 130th row with any 3 columns

In [ ]:
# object types of each column

In [ ]:
#Null values count in each column

In [ ]:
#Summary statistics

# Grouping

Grouping works similar to "group by" as in databases. Pandas also provides a "group by" function which serves the same purpose.

In [ ]:
fuel_price=df_cars.groupby('fuel-type')['price'].mean()

In [ ]:
fuel_price

In [ ]:
door_price=df_cars.groupby('num-of-doors')['price'].mean()

In [ ]:
door_price

In [ ]:
group=df_cars.groupby(['fuel-type','num-of-doors'])['price'].mean().reset_index()

In [ ]:
group

### Task

Find the total price according to each body style.

Hint: use <code>sum()</code> instead of <code>mean</code>.

In [ ]:
# write the code here

# Pivoting and Melting

**Pivoting**

In [ ]:
pivoted= pd.pivot_table(group,index='fuel-type',columns='num-of-doors', values='price',aggfunc='mean',fill_value=0)

In [ ]:
pivoted

In [ ]:
new= pivoted.reset_index()

In [ ]:
new

**Melting**

In [ ]:
melted= pd.melt(new,id_vars='fuel-type', value_name='Mean Price')

In [ ]:
melted